export const GET_PREFERENCES_SUCCESS = 'GET_PREFERENCES_SUCCESS';
export const GET_AGENT_SUCCESS = 'GET_AGENT_SUCCESS';
export const POST_SEND_MESSAGE_SUCCESS = 'POST_SEND_MESSAGE_SUCCESS';
export const POST_GENERATE_LEAD_SUCCESS = 'POST_GENERATE_LEAD_SUCCESS';
export const POST_DELETE_CHANNEL_SUCCESS = 'POST_DELETE_CHANNEL_SUCCESS';
